---
- hosts: all
  gather_facts: false
  tasks:
  #    - debug:
  #        var: hostvars[inventory_hostname]['ansible_os_type']
  # #  - name: Run this block when the server is Linux
   - debug:
       msg: "Hostname  is {{ inventory_hostname }} and OS type is {{hostvars[inventory_hostname]['ansible_os_type']}}"
     when: hostvars[inventory_hostname]['ansible_os_type'] == 'linux'

   - debug:
       msg: "Hostname  is {{ inventory_hostname }} and OS type is {{hostvars[inventory_hostname]['ansible_os_type']}}"
     when: hostvars[inventory_hostname]['ansible_os_type'] == 'windows'

   - set_stats:
       data:
         myvar: "test"
       aggregate: false 
       per_host: true 


  #  - name: Run this block when the server is Windows
  #    debug:
  #      msg: "Hostname  is {{ inventory_hostname }} and OS type is {{ hostvars.ansible_os_type }}"
  #    when: hostvars[inventory_hostname]['ansible_os_type'] == 'windows'
