---
- hosts: all
  gather_facts: false
  vars:
   my_var: "test"
  tasks:
    - name: Get IP Address
      win_shell:  (Get-NetIPAddress |?{$_.addressfamily -eq 'IPv4'}| select IPAddress).IPAddress
      register: ip_output
    
    - name: Variable to hold IPAddress
      set_fact:
        ip: "{{ ip_output.stdout }}"
      
    - name: Ping this IP Address
      win_shell:  ping {{ ip }}

      

